let mapleader=','

" Vim Plugged
" call plug#begin('$HOME/vimfiles/plugged')
" call plug#end()

" runtime! C:\Program\ Files\ (x86)\Vim\vim80\macros\matchit.vim

" Basic Settings
  set autoindent
  set backspace=2
  set colorcolumn=-0
  set cursorline
  set encoding=utf-8
  set expandtab
  set foldcolumn=1
  set foldmethod=indent
  set guifont:Consolas:h11.7:cANSI:qDRAFT
  set guioptions=e
  set ignorecase
  set incsearch
  set laststatus=2
  set list
  "set listchars=tab:>,eol:¬,extends:<,precedes:>,trail:·
  set listchars=tab:>,extends:<,precedes:>,trail:·
  set mouse=a
  set noautochdir
  set nocompatible
  set nomousehide
  set noswapfile
  set nowrap
  set nonumber
  set nojoinspaces
  set relativenumber
  set numberwidth=3
  set selection=inclusive
  set shiftwidth=2
  set showcmd
  set showmatch
  set smartcase
  set smartindent
  set smarttab
  "set sidescrolloff=50
  set splitbelow
  set splitright
  set synmaxcol=10000
  set tabstop=2
  set textwidth=80
  set undodir=C:\Users\jodden\vimfiles\undo\
  set undofile
  set undolevels=1000
  set undoreload=10000
  set backup
  set backupext=.bak
  set backupdir=C:\Users\jodden\vimfiles\backup\
  set diffopt+=context:3
  set wildignore+=*\\node_modules\\*,*\\bootstrap-*\\*,*\\jquery-*\\*

" Vimwiki settings
  " let g:vimwiki_url_maxsave = 0
  " let g:vimwiki_ext2synatx = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
  " let work_wiki = {}
  " let work_wiki.path = '~/Dropbox/work-wiki/'
  " let work_wiki.path_html = '~/Dropbox/work-wiki-html/'
  " let work_wiki.diary_rel_path = 'log/'
  " let work_wiki.syntax = 'markdown'
  " let work_wiki.ext = '.md'
  " let private_wiki = {}
  " let private_wiki.path = '~/Dropbox/private-wiki/'
  " let private_wiki.path_html = '~/Dropbox/private-wiki-html/'
  " let private_wiki.diary_rel_path = 'diary/'
  " let private_wiki.syntax = 'markdown'
  " let private_wiki.ext = '.md'
  " let g:vimwiki_list = [work_wiki, private_wiki]
  " let g:vimwiki_global_ext = 0

" Custom mappings
  nno <left> <nop>
  nno <right> <nop>
  nno <up> <nop>
  nno <down> <nop>
  ino <left> <nop>
  ino <right> <nop>
  ino <up> <nop>
  ino <down> <nop>
  nno <C-V> <C-V>
  " nno <leader>pi :PlugInstall<cr><C-L>
  " nno <leader>pu :PlugUpdate<cr><C-L>
  " nno <C-n><C-t> :NERDTreeToggle<cr>
  " ino <C-n><C-t> <esc>:NERDTreeToggle<cr><C-w><C-l>a
  nno <leader>ns <C-w><C-v>:enew <bar> setlocal buftype=nofile <bar> setlocal bufhidden=hide <bar> setlocal noswapfile <bar> setlocal nobuflisted<cr>
  " nno <leader>tc :VimwikiTOC<cr>
  nno G Gzz
  nno } }zz
  nno { {zz
  nno N Nzzzv
  nno n nzzzv
  nno * *zzzv
  nno # #zzzv

" Set thing near the end in case of other plugins changing settings
  filetype plugin indent on
  syntax on

" Auto commands
  au FileType * set formatoptions=cqwnjb
  au BufNewFile,BufRead *.svg setf svg
  au BufNewFile,BufRead *.ashx setf cs
  au BufNewFile,BufRead *.cs setf cs
